name: Trekker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  path_provider: any
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/FirstPage.png
    - assets/images/EuropaCarusel.png
    - assets/images/AustraliaCarusel.png
    - assets/images/NorthAmericaCarusel.png
    - assets/images/SouthAmericaCarusel.jpg
    - assets/images/AfricaCarusel.jpg
    - assets/images/AsiaCarusel.png
    - assets/images/AntarcticaCarusel.png
    - assets/images/icon_app.png
    - assets/TrakkerDB.db
